<?xml version="1.0"?>
<robot name="safer_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ── Constants ─────────────────────────────────────────────────────────── -->
  <xacro:property name="wheel_radius"   value="0.085"/>
  <xacro:property name="wheel_width"    value="0.05"/>
  <xacro:property name="wheel_base"     value="0.45"/>
  <xacro:property name="chassis_length" value="0.60"/>
  <xacro:property name="chassis_width"  value="0.45"/>
  <xacro:property name="chassis_height" value="0.15"/>
  <xacro:property name="chassis_mass"   value="8.0"/>
  <xacro:property name="wheel_mass"     value="0.5"/>

  <!-- ── Materials ─────────────────────────────────────────────────────────── -->
  <material name="dark_grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <!-- ── Inertia macros ─────────────────────────────────────────────────────── -->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
               iyy="${m*(x*x+z*z)/12}" iyz="0"
               izz="${m*(x*x+y*y)/12}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
               iyy="${m*(3*r*r+h*h)/12}" iyz="0"
               izz="${m*r*r/2}"/>
    </inertial>
  </xacro:macro>

  <!-- ── Base footprint ─────────────────────────────────────────────────────── -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child  link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ── Chassis ────────────────────────────────────────────────────────────── -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${chassis_mass}"
                       x="${chassis_length}"
                       y="${chassis_width}"
                       z="${chassis_height}"/>
  </link>

  <!-- ── Wheel macro ────────────────────────────────────────────────────────── -->
  <xacro:macro name="wheel" params="name x_offset y_offset">
    <link name="${name}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${name}_wheel"/>
      <origin xyz="${x_offset} ${y_offset} ${-chassis_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel name="front_left"  x_offset=" 0.20" y_offset=" ${wheel_base/2}"/>
  <xacro:wheel name="front_right" x_offset=" 0.20" y_offset="-${wheel_base/2}"/>
  <xacro:wheel name="rear_left"   x_offset="-0.20" y_offset=" ${wheel_base/2}"/>
  <xacro:wheel name="rear_right"  x_offset="-0.20" y_offset="-${wheel_base/2}"/>

  <!-- ── Depth camera ───────────────────────────────────────────────────────── -->
  <link name="camera_link">
    <visual>
      <geometry><box size="0.04 0.12 0.03"/></geometry>
      <material name="dark_grey"/>
    </visual>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="camera_link"/>
    <origin xyz="0.28 0.0 0.20" rpy="0 0 0"/>
  </joint>
  <link name="camera_depth_frame"/>
  <joint name="camera_depth_joint" type="fixed">
    <parent link="camera_link"/>
    <child  link="camera_depth_frame"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- ── LiDAR ──────────────────────────────────────────────────────────────── -->
  <link name="laser">
    <visual>
      <geometry><cylinder radius="0.05" length="0.07"/></geometry>
      <material name="orange"/>
    </visual>
  </link>
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="laser"/>
    <origin xyz="0 0 0.15" rpy="0 0 0"/>
  </joint>

  <!-- ── Ultrasonic sensors ─────────────────────────────────────────────────── -->
  <xacro:macro name="ultrasonic" params="name x y z rpy">
    <link name="${name}_ultrasonic">
      <visual>
        <geometry><box size="0.02 0.04 0.02"/></geometry>
        <material name="dark_grey"/>
      </visual>
    </link>
    <joint name="${name}_ultrasonic_joint" type="fixed">
      <parent link="base_link"/>
      <child  link="${name}_ultrasonic"/>
      <origin xyz="${x} ${y} ${z}" rpy="${rpy}"/>
    </joint>
  </xacro:macro>

  <xacro:ultrasonic name="front_left"  x="0.30"  y=" 0.15" z="0.05" rpy="0 0 0"/>
  <xacro:ultrasonic name="front_right" x="0.30"  y="-0.15" z="0.05" rpy="0 0 0"/>
  <xacro:ultrasonic name="rear"        x="-0.30" y="0"     z="0.05" rpy="0 0 ${pi}"/>

  <!-- ── Gazebo plugins ─────────────────────────────────────────────────────── -->
  <gazebo>
    <plugin name="differential_drive_controller"
            filename="libgazebo_ros_diff_drive.so">
      <leftJoint>front_left_wheel_joint</leftJoint>
      <rightJoint>front_right_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_base}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <publishWheelTF>false</publishWheelTF>
      <publishOdom>true</publishOdom>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
    </plugin>
  </gazebo>

  <gazebo reference="laser">
    <sensor type="ray" name="lidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <min_angle>-${pi}</min_angle>
            <max_angle>${pi}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
        </range>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>laser</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>
